INSERT INTO ESTADOS (ID,SIGLA,ESTADO,PAISES_ID) VALUES (
12,'AC','ACRE',1058);
INSERT INTO ESTADOS (ID,SIGLA,ESTADO,PAISES_ID) VALUES (
27,'AL','ALAGOAS',1058);
INSERT INTO ESTADOS (ID,SIGLA,ESTADO,PAISES_ID) VALUES (
13,'AM','AMAZONAS',1058);
INSERT INTO ESTADOS (ID,SIGLA,ESTADO,PAISES_ID) VALUES (
16,'AP','AMAPA',1058);
INSERT INTO ESTADOS (ID,SIGLA,ESTADO,PAISES_ID) VALUES (
29,'BA','BAHIA',1058);
INSERT INTO ESTADOS (ID,SIGLA,ESTADO,PAISES_ID) VALUES (
23,'CE','CEARA',1058);
INSERT INTO ESTADOS (ID,SIGLA,ESTADO,PAISES_ID) VALUES (
53,'DF','DISTRITO FEDERAL',1058);
INSERT INTO ESTADOS (ID,SIGLA,ESTADO,PAISES_ID) VALUES (
32,'ES','ESPIRITO SANTO',1058);
INSERT INTO ESTADOS (ID,SIGLA,ESTADO,PAISES_ID) VALUES (
52,'GO','GOIAS',1058);
INSERT INTO ESTADOS (ID,SIGLA,ESTADO,PAISES_ID) VALUES (
21,'MA','MARANHAO',1058);
INSERT INTO ESTADOS (ID,SIGLA,ESTADO,PAISES_ID) VALUES (
31,'MG','MINAS GERAIS',1058);
INSERT INTO ESTADOS (ID,SIGLA,ESTADO,PAISES_ID) VALUES (
50,'MS','MATO GROSSO DO SUL',1058);
INSERT INTO ESTADOS (ID,SIGLA,ESTADO,PAISES_ID) VALUES (
51,'MT','MATO GROSSO',1058);
INSERT INTO ESTADOS (ID,SIGLA,ESTADO,PAISES_ID) VALUES (
15,'PA','PARA',1058);
INSERT INTO ESTADOS (ID,SIGLA,ESTADO,PAISES_ID) VALUES (
25,'PB','PARAIBA',1058);
INSERT INTO ESTADOS (ID,SIGLA,ESTADO,PAISES_ID) VALUES (
26,'PE','PERNAMBUCO',1058);
INSERT INTO ESTADOS (ID,SIGLA,ESTADO,PAISES_ID) VALUES (
22,'PI','PIAUI',1058);
INSERT INTO ESTADOS (ID,SIGLA,ESTADO,PAISES_ID) VALUES (
41,'PR','PARANA',1058);
INSERT INTO ESTADOS (ID,SIGLA,ESTADO,PAISES_ID) VALUES (
33,'RJ','RIO DE JANEIRO',1058);
INSERT INTO ESTADOS (ID,SIGLA,ESTADO,PAISES_ID) VALUES (
24,'RN','RIO GRANDE DO NORTE',1058);
INSERT INTO ESTADOS (ID,SIGLA,ESTADO,PAISES_ID) VALUES (
11,'RO','RONDONIA',1058);
INSERT INTO ESTADOS (ID,SIGLA,ESTADO,PAISES_ID) VALUES (
14,'RR','RORAIMA',1058);
INSERT INTO ESTADOS (ID,SIGLA,ESTADO,PAISES_ID) VALUES (
43,'RS','RIO GRANDE DO SUL',1058);
INSERT INTO ESTADOS (ID,SIGLA,ESTADO,PAISES_ID) VALUES (
42,'SC','SANTA CATARINA',1058);
INSERT INTO ESTADOS (ID,SIGLA,ESTADO,PAISES_ID) VALUES (
28,'SE','SERGIPE',1058);
INSERT INTO ESTADOS (ID,SIGLA,ESTADO,PAISES_ID) VALUES (
35,'SP','SAO PAULO',1058);
INSERT INTO ESTADOS (ID,SIGLA,ESTADO,PAISES_ID) VALUES (
17,'TO','TOCANTINS',1058);
INSERT INTO ESTADOS (ID,SIGLA,ESTADO,PAISES_ID) VALUES (
77,'EX','EXTERIOR',1058);
