INSERT INTO PAISES (ID,NOME) VALUES (
1058,'BRASIL');
INSERT INTO PAISES (ID,NOME) VALUES (
132,'AFEGANISTAO');
INSERT INTO PAISES (ID,NOME) VALUES (
175,'ALBANIA, REPUBLICA DA ');
INSERT INTO PAISES (ID,NOME) VALUES (
230,'ALEMANHA ');
INSERT INTO PAISES (ID,NOME) VALUES (
310,'BURKINA FASO ');
INSERT INTO PAISES (ID,NOME) VALUES (
370,'ANDORRA');
INSERT INTO PAISES (ID,NOME) VALUES (
400,'ANGOLA');
INSERT INTO PAISES (ID,NOME) VALUES (
418,'ANGUILLA ');
INSERT INTO PAISES (ID,NOME) VALUES (
434,'ANTIGUA E BARBUDA ');
INSERT INTO PAISES (ID,NOME) VALUES (
477,'ANTILHAS HOLANDESAS ');
INSERT INTO PAISES (ID,NOME) VALUES (
531,'ARABIA SAUDITA ');
INSERT INTO PAISES (ID,NOME) VALUES (
590,'ARGELIA ');
INSERT INTO PAISES (ID,NOME) VALUES (
639,'ARGENTINA');
INSERT INTO PAISES (ID,NOME) VALUES (
647,'ARMENIA, REPUBLICA DA ');
INSERT INTO PAISES (ID,NOME) VALUES (
655,'ARUBA ');
INSERT INTO PAISES (ID,NOME) VALUES (
698,'AUSTRALIA');
INSERT INTO PAISES (ID,NOME) VALUES (
728,'AUSTRIA');
INSERT INTO PAISES (ID,NOME) VALUES (
736,'AZERBAIJAO, REPUBLICA DO');
INSERT INTO PAISES (ID,NOME) VALUES (
779,'BAHAMAS, ILHAS ');
INSERT INTO PAISES (ID,NOME) VALUES (
809,'BAHREIN, ILHAS ');
INSERT INTO PAISES (ID,NOME) VALUES (
817,'BANGLADESH ');
INSERT INTO PAISES (ID,NOME) VALUES (
833,'BARBADOS ');
INSERT INTO PAISES (ID,NOME) VALUES (
850,'BELARUS, REPUBLICA DA ');
INSERT INTO PAISES (ID,NOME) VALUES (
876,'BELGICA');
INSERT INTO PAISES (ID,NOME) VALUES (
884,'BELIZE');
INSERT INTO PAISES (ID,NOME) VALUES (
906,'BERMUDAS');
INSERT INTO PAISES (ID,NOME) VALUES (
930,'MIANMAR (BIRMANIA)');
INSERT INTO PAISES (ID,NOME) VALUES (
973,'BOLIVIA, ESTADO PLURINACIONAL DA ');
INSERT INTO PAISES (ID,NOME) VALUES (
981,'BOSNIA-HERZEGOVINA (REPUBLICA DA)');
INSERT INTO PAISES (ID,NOME) VALUES (
1015,'BOTSUANA');
INSERT INTO PAISES (ID,NOME) VALUES (
1082,'BRUNEI');
INSERT INTO PAISES (ID,NOME) VALUES (
1112,'BULGARIA, REPUBLICA DA ');
INSERT INTO PAISES (ID,NOME) VALUES (
1155,'BURUNDI');
INSERT INTO PAISES (ID,NOME) VALUES (
1198,'BUTAO');
INSERT INTO PAISES (ID,NOME) VALUES (
1279,'CABO VERDE, REPUBLICA DE ');
INSERT INTO PAISES (ID,NOME) VALUES (
1376,'CAYMAN, ILHAS ');
INSERT INTO PAISES (ID,NOME) VALUES (
1414,'CAMBOJA ');
INSERT INTO PAISES (ID,NOME) VALUES (
1457,'CAMAROES');
INSERT INTO PAISES (ID,NOME) VALUES (
1490,'CANADA');
INSERT INTO PAISES (ID,NOME) VALUES (
1504,'GUERNSEY, ILHA DO CANAL (INCLUI ALDERNEY E SARK)');
INSERT INTO PAISES (ID,NOME) VALUES (
1508,'JERSEY, ILHA DO CANAL ');
INSERT INTO PAISES (ID,NOME) VALUES (
1511,'CANARIAS, ILHAS ');
INSERT INTO PAISES (ID,NOME) VALUES (
1538,'CAZAQUISTAO, REPUBLICA DO ');
INSERT INTO PAISES (ID,NOME) VALUES (
1546,'CATAR ');
INSERT INTO PAISES (ID,NOME) VALUES (
1589,'CHILE');
INSERT INTO PAISES (ID,NOME) VALUES (
1600,'CHINA, REPUBLICA POPULAR ');
INSERT INTO PAISES (ID,NOME) VALUES (
1619,'FORMOSA (TAIWAN) ');
INSERT INTO PAISES (ID,NOME) VALUES (
1635,'CHIPRE ');
INSERT INTO PAISES (ID,NOME) VALUES (
1651,'COCOS(KEELING),ILHAS ');
INSERT INTO PAISES (ID,NOME) VALUES (
1694,'COLOMBIA ');
INSERT INTO PAISES (ID,NOME) VALUES (
1732,'COMORES, ILHAS ');
INSERT INTO PAISES (ID,NOME) VALUES (
1775,'CONGO ');
INSERT INTO PAISES (ID,NOME) VALUES (
1830,'COOK, ILHAS ');
INSERT INTO PAISES (ID,NOME) VALUES (
1872,'COREIA (DO NORTE), REP.POP.DEMOCRATICA ');
INSERT INTO PAISES (ID,NOME) VALUES (
1902,'COREIA (DO SUL), REPUBLICA DA ');
INSERT INTO PAISES (ID,NOME) VALUES (
1937,'COSTA DO MARFIM ');
INSERT INTO PAISES (ID,NOME) VALUES (
1953,'CROACIA (REPUBLICA DA)');
INSERT INTO PAISES (ID,NOME) VALUES (
1961,'COSTA RICA ');
INSERT INTO PAISES (ID,NOME) VALUES (
1988,'COVEITE ');
INSERT INTO PAISES (ID,NOME) VALUES (
1996,'CUBA ');
INSERT INTO PAISES (ID,NOME) VALUES (
2291,'BENIN');
INSERT INTO PAISES (ID,NOME) VALUES (
2321,'DINAMARCA');
INSERT INTO PAISES (ID,NOME) VALUES (
2356,'DOMINICA,ILHA ');
INSERT INTO PAISES (ID,NOME) VALUES (
2399,'EQUADOR ');
INSERT INTO PAISES (ID,NOME) VALUES (
2402,'EGITO');
INSERT INTO PAISES (ID,NOME) VALUES (
2437,'ERITREIA');
INSERT INTO PAISES (ID,NOME) VALUES (
2445,'EMIRADOS ARABES UNIDOS ');
INSERT INTO PAISES (ID,NOME) VALUES (
2453,'ESPANHA ');
INSERT INTO PAISES (ID,NOME) VALUES (
2461,'ESLOVENIA, REPUBLICA DA ');
INSERT INTO PAISES (ID,NOME) VALUES (
2470,'ESLOVACA, REPUBLICA ');
INSERT INTO PAISES (ID,NOME) VALUES (
2496,'ESTADOS UNIDOS');
INSERT INTO PAISES (ID,NOME) VALUES (
2518,'ESTONIA, REPUBLICA DA ');
INSERT INTO PAISES (ID,NOME) VALUES (
2534,'ETIOPIA');
INSERT INTO PAISES (ID,NOME) VALUES (
2550,'FALKLAND (ILHAS MALVINAS)');
INSERT INTO PAISES (ID,NOME) VALUES (
2593,'FEROE, ILHAS ');
INSERT INTO PAISES (ID,NOME) VALUES (
2674,'FILIPINAS');
INSERT INTO PAISES (ID,NOME) VALUES (
2712,'FINLANDIA ');
INSERT INTO PAISES (ID,NOME) VALUES (
2755,'FRANCA');
INSERT INTO PAISES (ID,NOME) VALUES (
2810,'GABAO');
INSERT INTO PAISES (ID,NOME) VALUES (
2852,'GAMBIA ');
INSERT INTO PAISES (ID,NOME) VALUES (
2895,'GANA ');
INSERT INTO PAISES (ID,NOME) VALUES (
2917,'GEORGIA, REPUBLICA DA ');
INSERT INTO PAISES (ID,NOME) VALUES (
2933,'GIBRALTAR');
INSERT INTO PAISES (ID,NOME) VALUES (
2976,'GRANADA');
INSERT INTO PAISES (ID,NOME) VALUES (
3018,'GRECIA');
INSERT INTO PAISES (ID,NOME) VALUES (
3050,'GROENLANDIA ');
INSERT INTO PAISES (ID,NOME) VALUES (
3093,'GUADALUPE');
INSERT INTO PAISES (ID,NOME) VALUES (
3131,'GUAM');
INSERT INTO PAISES (ID,NOME) VALUES (
3174,'GUATEMALA');
INSERT INTO PAISES (ID,NOME) VALUES (
3255,'GUIANA FRANCESA ');
INSERT INTO PAISES (ID,NOME) VALUES (
3298,'GUINE ');
INSERT INTO PAISES (ID,NOME) VALUES (
3310,'GUINE-EQUATORIAL ');
INSERT INTO PAISES (ID,NOME) VALUES (
3344,'GUINE-BISSAU ');
INSERT INTO PAISES (ID,NOME) VALUES (
3379,'GUIANA');
INSERT INTO PAISES (ID,NOME) VALUES (
3417,'HAITI ');
INSERT INTO PAISES (ID,NOME) VALUES (
3450,'HONDURAS');
INSERT INTO PAISES (ID,NOME) VALUES (
3514,'HONG KONG ');
INSERT INTO PAISES (ID,NOME) VALUES (
3557,'HUNGRIA, REPUBLICA DA ');
INSERT INTO PAISES (ID,NOME) VALUES (
3573,'IEMEN');
INSERT INTO PAISES (ID,NOME) VALUES (
3595,'MAN, ILHA DE ');
INSERT INTO PAISES (ID,NOME) VALUES (
3611,'INDIA');
INSERT INTO PAISES (ID,NOME) VALUES (
3654,'INDONESIA ');
INSERT INTO PAISES (ID,NOME) VALUES (
3697,'IRAQUE');
INSERT INTO PAISES (ID,NOME) VALUES (
3727,'IRA, REPUBLICA ISLAMICA DO ');
INSERT INTO PAISES (ID,NOME) VALUES (
3751,'IRLANDA');
INSERT INTO PAISES (ID,NOME) VALUES (
3794,'ISLANDIA ');
INSERT INTO PAISES (ID,NOME) VALUES (
3832,'ISRAEL');
INSERT INTO PAISES (ID,NOME) VALUES (
3867,'ITALIA');
INSERT INTO PAISES (ID,NOME) VALUES (
3913,'JAMAICA');
INSERT INTO PAISES (ID,NOME) VALUES (
3964,'JOHNSTON, ILHAS ');
INSERT INTO PAISES (ID,NOME) VALUES (
3999,'JAPAO ');
INSERT INTO PAISES (ID,NOME) VALUES (
4111,'KIRIBATI');
INSERT INTO PAISES (ID,NOME) VALUES (
4200,'LAOS, REP.POP.DEMOCR.DO ');
INSERT INTO PAISES (ID,NOME) VALUES (
4235,'LEBUAN,ILHAS ');
INSERT INTO PAISES (ID,NOME) VALUES (
4260,'LESOTO');
INSERT INTO PAISES (ID,NOME) VALUES (
4278,'LETONIA, REPUBLICA DA ');
INSERT INTO PAISES (ID,NOME) VALUES (
4316,'LIBANO');
INSERT INTO PAISES (ID,NOME) VALUES (
4340,'LIBERIA');
INSERT INTO PAISES (ID,NOME) VALUES (
4383,'LIBIA');
INSERT INTO PAISES (ID,NOME) VALUES (
4405,'LIECHTENSTEIN');
INSERT INTO PAISES (ID,NOME) VALUES (
4421,'LITUANIA, REPUBLICA DA ');
INSERT INTO PAISES (ID,NOME) VALUES (
4456,'LUXEMBURGO');
INSERT INTO PAISES (ID,NOME) VALUES (
4472,'MACAU');
INSERT INTO PAISES (ID,NOME) VALUES (
4499,'MACEDONIA, ANT.REP.IUGOSLAVA');
INSERT INTO PAISES (ID,NOME) VALUES (
4502,'MADAGASCAR');
INSERT INTO PAISES (ID,NOME) VALUES (
4525,'MADEIRA, ILHA DA ');
INSERT INTO PAISES (ID,NOME) VALUES (
4553,'MALASIA');
INSERT INTO PAISES (ID,NOME) VALUES (
4588,'MALAVI');
INSERT INTO PAISES (ID,NOME) VALUES (
4618,'MALDIVAS');
INSERT INTO PAISES (ID,NOME) VALUES (
4642,'MALI');
INSERT INTO PAISES (ID,NOME) VALUES (
4677,'MALTA');
INSERT INTO PAISES (ID,NOME) VALUES (
4723,'MARIANAS DO NORTE');
INSERT INTO PAISES (ID,NOME) VALUES (
4740,'MARROCOS');
INSERT INTO PAISES (ID,NOME) VALUES (
4766,'MARSHALL,ILHAS');
INSERT INTO PAISES (ID,NOME) VALUES (
4774,'MARTINICA');
INSERT INTO PAISES (ID,NOME) VALUES (
4855,'MAURICIO');
INSERT INTO PAISES (ID,NOME) VALUES (
4880,'MAURITANIA');
INSERT INTO PAISES (ID,NOME) VALUES (
4885,'MAYOTTE (ILHAS FRANCESAS)');
INSERT INTO PAISES (ID,NOME) VALUES (
4901,'MIDWAY, ILHAS');
INSERT INTO PAISES (ID,NOME) VALUES (
4936,'MEXICO');
INSERT INTO PAISES (ID,NOME) VALUES (
4944,'MOLDAVIA, REPUBLICA DA ');
INSERT INTO PAISES (ID,NOME) VALUES (
4952,'MONACO');
INSERT INTO PAISES (ID,NOME) VALUES (
4979,'MONGOLIA');
INSERT INTO PAISES (ID,NOME) VALUES (
4985,'MONTENEGRO');
INSERT INTO PAISES (ID,NOME) VALUES (
4995,'MICRONESIA');
INSERT INTO PAISES (ID,NOME) VALUES (
5010,'MONTSERRAT,ILHAS ');
INSERT INTO PAISES (ID,NOME) VALUES (
5053,'MOCAMBIQUE');
INSERT INTO PAISES (ID,NOME) VALUES (
5070,'NAMIBIA');
INSERT INTO PAISES (ID,NOME) VALUES (
5088,'NAURU');
INSERT INTO PAISES (ID,NOME) VALUES (
5118,'CHRISTMAS,ILHA (NAVIDAD)');
INSERT INTO PAISES (ID,NOME) VALUES (
5177,'NEPAL');
INSERT INTO PAISES (ID,NOME) VALUES (
5215,'NICARAGUA');
INSERT INTO PAISES (ID,NOME) VALUES (
5258,'NIGER ');
INSERT INTO PAISES (ID,NOME) VALUES (
5282,'NIGERIA');
INSERT INTO PAISES (ID,NOME) VALUES (
5312,'NIUE,ILHA');
INSERT INTO PAISES (ID,NOME) VALUES (
5355,'NORFOLK,ILHA ');
INSERT INTO PAISES (ID,NOME) VALUES (
5380,'NORUEGA');
INSERT INTO PAISES (ID,NOME) VALUES (
5428,'NOVA CALEDONIA');
INSERT INTO PAISES (ID,NOME) VALUES (
5452,'PAPUA NOVA GUINE ');
INSERT INTO PAISES (ID,NOME) VALUES (
5487,'NOVA ZELANDIA');
INSERT INTO PAISES (ID,NOME) VALUES (
5517,'VANUATU');
INSERT INTO PAISES (ID,NOME) VALUES (
5568,'OMA');
INSERT INTO PAISES (ID,NOME) VALUES (
5665,'PACIFICO,ILHAS DO (POSSESSAO DOS EUA)');
INSERT INTO PAISES (ID,NOME) VALUES (
5738,'PAISES BAIXOS (HOLANDA)');
INSERT INTO PAISES (ID,NOME) VALUES (
5762,'PAQUISTAO');
INSERT INTO PAISES (ID,NOME) VALUES (
5800,'PANAMA');
INSERT INTO PAISES (ID,NOME) VALUES (
5860,'PARAGUAI');
INSERT INTO PAISES (ID,NOME) VALUES (
5894,'PERU');
INSERT INTO PAISES (ID,NOME) VALUES (
5932,'PITCAIRN,ILHA');
INSERT INTO PAISES (ID,NOME) VALUES (
5991,'POLINESIA FRANCESA');
INSERT INTO PAISES (ID,NOME) VALUES (
6033,'POLONIA, REPUBLICA DA');
INSERT INTO PAISES (ID,NOME) VALUES (
6076,'PORTUGAL');
INSERT INTO PAISES (ID,NOME) VALUES (
6114,'PORTO RICO ');
INSERT INTO PAISES (ID,NOME) VALUES (
6238,'QUENIA');
INSERT INTO PAISES (ID,NOME) VALUES (
6254,'QUIRGUIZ, REPUBLICA ');
INSERT INTO PAISES (ID,NOME) VALUES (
6289,'REINO UNIDO ');
INSERT INTO PAISES (ID,NOME) VALUES (
6408,'REPUBLICA CENTRO-AFRICANA ');
INSERT INTO PAISES (ID,NOME) VALUES (
6475,'REPUBLICA DOMINICANA ');
INSERT INTO PAISES (ID,NOME) VALUES (
6602,'REUNIAO, ILHA ');
INSERT INTO PAISES (ID,NOME) VALUES (
6653,'ZIMBABUE');
INSERT INTO PAISES (ID,NOME) VALUES (
6700,'ROMENIA');
INSERT INTO PAISES (ID,NOME) VALUES (
6750,'RUANDA');
INSERT INTO PAISES (ID,NOME) VALUES (
6769,'RUSSIA, FEDERACAO DA ');
INSERT INTO PAISES (ID,NOME) VALUES (
6777,'SALOMAO, ILHAS ');
INSERT INTO PAISES (ID,NOME) VALUES (
6858,'SAARA OCIDENTAL ');
INSERT INTO PAISES (ID,NOME) VALUES (
6874,'EL SALVADOR ');
INSERT INTO PAISES (ID,NOME) VALUES (
6904,'SAMOA');
INSERT INTO PAISES (ID,NOME) VALUES (
6912,'SAMOA AMERICANA ');
INSERT INTO PAISES (ID,NOME) VALUES (
6955,'SAO CRISTOVAO E NEVES,ILHAS ');
INSERT INTO PAISES (ID,NOME) VALUES (
6971,'SAN MARINO');
INSERT INTO PAISES (ID,NOME) VALUES (
7005,'SAO PEDRO E MIQUELON ');
INSERT INTO PAISES (ID,NOME) VALUES (
7056,'SAO VICENTE E GRANADINAS ');
INSERT INTO PAISES (ID,NOME) VALUES (
7102,'SANTA HELENA ');
INSERT INTO PAISES (ID,NOME) VALUES (
7153,'SANTA LUCIA ');
INSERT INTO PAISES (ID,NOME) VALUES (
7200,'SAO TOME E PRINCIPE, ILHAS ');
INSERT INTO PAISES (ID,NOME) VALUES (
7285,'SENEGAL');
INSERT INTO PAISES (ID,NOME) VALUES (
7315,'SEYCHELLES');
INSERT INTO PAISES (ID,NOME) VALUES (
7358,'SERRA LEOA ');
INSERT INTO PAISES (ID,NOME) VALUES (
7370,'SERVIA ');
INSERT INTO PAISES (ID,NOME) VALUES (
7412,'CINGAPURA');
INSERT INTO PAISES (ID,NOME) VALUES (
7447,'SIRIA, REPUBLICA ARABE DA ');
INSERT INTO PAISES (ID,NOME) VALUES (
7480,'SOMALIA');
INSERT INTO PAISES (ID,NOME) VALUES (
7501,'SRI LANKA ');
INSERT INTO PAISES (ID,NOME) VALUES (
7544,'SUAZILANDIA ');
INSERT INTO PAISES (ID,NOME) VALUES (
7560,'AFRICA DO SUL ');
INSERT INTO PAISES (ID,NOME) VALUES (
7641,'SUECIA');
INSERT INTO PAISES (ID,NOME) VALUES (
7595,'SUDAO ');
INSERT INTO PAISES (ID,NOME) VALUES (
7676,'SUICA');
INSERT INTO PAISES (ID,NOME) VALUES (
7706,'SURINAME');
INSERT INTO PAISES (ID,NOME) VALUES (
7722,'TADJIQUISTAO, REPUBLICA DO ');
INSERT INTO PAISES (ID,NOME) VALUES (
7765,'TAILANDIA');
INSERT INTO PAISES (ID,NOME) VALUES (
7803,'TANZANIA, REP.UNIDA DA');
INSERT INTO PAISES (ID,NOME) VALUES (
7820,'TERRITORIO BRIT.OC.INDI');
INSERT INTO PAISES (ID,NOME) VALUES (
7838,'DJIBUTI');
INSERT INTO PAISES (ID,NOME) VALUES (
7889,'CHADE');
INSERT INTO PAISES (ID,NOME) VALUES (
7919,'TCHECA, REPUBLICA ');
INSERT INTO PAISES (ID,NOME) VALUES (
7951,'TIMOR LESTE ');
INSERT INTO PAISES (ID,NOME) VALUES (
8001,'TOGO');
INSERT INTO PAISES (ID,NOME) VALUES (
8052,'TOQUELAU,ILHAS ');
INSERT INTO PAISES (ID,NOME) VALUES (
8109,'TONGA');
INSERT INTO PAISES (ID,NOME) VALUES (
8150,'TRINIDAD E TOBAGO ');
INSERT INTO PAISES (ID,NOME) VALUES (
8206,'TUNISIA ');
INSERT INTO PAISES (ID,NOME) VALUES (
8230,'TURCAS E CAICOS,ILHAS ');
INSERT INTO PAISES (ID,NOME) VALUES (
8249,'TURCOMENISTAO, REPUBLICA DO ');
INSERT INTO PAISES (ID,NOME) VALUES (
8273,'TURQUIA');
INSERT INTO PAISES (ID,NOME) VALUES (
8281,'TUVALU');
INSERT INTO PAISES (ID,NOME) VALUES (
8311,'UCRANIA ');
INSERT INTO PAISES (ID,NOME) VALUES (
8338,'UGANDA');
INSERT INTO PAISES (ID,NOME) VALUES (
8451,'URUGUAI');
INSERT INTO PAISES (ID,NOME) VALUES (
8478,'UZBEQUISTAO, REPUBLICA DO');
INSERT INTO PAISES (ID,NOME) VALUES (
8486,'VATICANO, EST.DA CIDADE DO');
INSERT INTO PAISES (ID,NOME) VALUES (
8508,'VENEZUELA ');
INSERT INTO PAISES (ID,NOME) VALUES (
8583,'VIETNA');
INSERT INTO PAISES (ID,NOME) VALUES (
8630,'VIRGENS,ILHAS (BRITANICAS)');
INSERT INTO PAISES (ID,NOME) VALUES (
8664,'VIRGENS,ILHAS (E.U.A.)');
INSERT INTO PAISES (ID,NOME) VALUES (
8702,'FIJI');
INSERT INTO PAISES (ID,NOME) VALUES (
8737,'WAKE, ILHA ');
INSERT INTO PAISES (ID,NOME) VALUES (
8885,'CONGO, REPUBLICA DEMOCRATICA DO ');
INSERT INTO PAISES (ID,NOME) VALUES (
8907,'ZAMBIA');
