"""empty message

Revision ID: 96411796d973
Revises: d8fdbdd9ac39
Create Date: 2019-06-22 20:40:35.915998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96411796d973'
down_revision = 'd8fdbdd9ac39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfis_banidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('perfis_banidos')
    # ### end Alembic commands ###
