"""empty message

Revision ID: aa21de8887ae
Revises: 
Create Date: 2019-06-20 15:07:11.536574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa21de8887ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descricao')
    )
    op.create_table('paises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('sigla', sa.String(length=2), nullable=True),
    sa.Column('pais_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pais_id'], ['paises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigla')
    )
    op.create_table('cidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('estado_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estado_id'], ['estados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perfis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(), nullable=False),
    sa.Column('nome_fantasia', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('logradouro', sa.String(), nullable=False),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('sobre', sa.String(), nullable=False),
    sa.Column('interesses', sa.String(), nullable=True),
    sa.Column('cidade_id', sa.Integer(), nullable=False),
    sa.Column('logo', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cidade_id'], ['cidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('razao_social')
    )
    op.create_table('postagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('conteudo', sa.String(), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('hora', sa.String(), nullable=False),
    sa.Column('media_avaliacao', sa.Float(), nullable=True),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sugestoes_categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('postagem_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfis.id'], ),
    sa.ForeignKeyConstraint(['postagem_id'], ['postagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.String(), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('hora', sa.String(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('postagem_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfis.id'], ),
    sa.ForeignKeyConstraint(['postagem_id'], ['postagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentarios')
    op.drop_table('avaliacoes')
    op.drop_table('sugestoes_categorias')
    op.drop_table('postagens')
    op.drop_table('perfis')
    op.drop_table('cidades')
    op.drop_table('estados')
    op.drop_table('paises')
    op.drop_table('categorias')
    # ### end Alembic commands ###
